apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: heimdall-credentials
  labels:
    app.kubernetes.io/name: heimdall-syncer
    app.kubernetes.io/component: syncer
    app.kubernetes.io/part-of: heimdall
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: heimdall-secrets-native
    creationPolicy: Owner
  data:
    # Background workers do not require API Key hashes
    - secretKey: HEIMDALL_DB_URL
      remoteRef:
        key: heimdall/prod/database
        property: url
    - secretKey: HEIMDALL_REDIS_URL
      remoteRef:
        key: heimdall/prod/redis
        property: url
