apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall-data-plane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: heimdall-data-plane
    app.kubernetes.io/component: data-plane
    app.kubernetes.io/part-of: heimdall
  annotations:
    # Wave 3: Deploys the components only after all foundational tools are fully ready
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/rafaeljc/heimdall.git'
    targetRevision: HEAD
    path: infra/gitops/workloads/data-plane/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: heimdall-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
