apiVersion: v1
kind: Service
metadata:
  name: heimdall-data-plane
  labels:
    app.kubernetes.io/name: heimdall-data-plane
    app.kubernetes.io/component: data-plane
    app.kubernetes.io/part-of: heimdall
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: heimdall-data-plane
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
      # Hints the underlying infrastructure/Service Mesh that this is gRPC traffic (HTTP/2)
      appProtocol: grpc
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
      appProtocol: http
