apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: heimdall-credentials
  labels:
    app.kubernetes.io/name: heimdall-control-plane
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: heimdall
spec:
  # Continuous Compliance: Automatically fetches new passwords if rotated in AWS
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: heimdall-secrets-native
    creationPolicy: Owner
  data:
    - secretKey: HEIMDALL_DB_URL
      remoteRef:
        key: heimdall/prod/database
        property: url
    - secretKey: HEIMDALL_REDIS_URL
      remoteRef:
        key: heimdall/prod/redis
        property: url
    - secretKey: HEIMDALL_SERVER_CONTROL_API_KEY_HASH
      remoteRef:
        key: heimdall/prod/api-keys
        property: control_plane_hash
