apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- cluster-secret-store.yaml
- external-secret.yaml
- migration-job.yaml
- service-public.yaml
- ../../../../../../migrations

patches:
- path: deployment-patch.yaml

# Kustomize appends a hash to the ConfigMap name. 
# Changing these values will automatically trigger a rolling restart of the pods.
      # Enforce TLS on the Control Plane API
configMapGenerator:
- literals:
  - HEIMDALL_APP_ENV=production
  - HEIMDALL_APP_LOG_LEVEL=info
  - HEIMDALL_APP_LOG_FORMAT=json
  - HEIMDALL_DB_SSL_MODE=require
  - HEIMDALL_REDIS_TLS_ENABLED=true
  - HEIMDALL_SERVER_CONTROL_TLS_ENABLED=true
  - HEIMDALL_SERVER_CONTROL_TLS_CERT_PATH=/etc/heimdall/certs/tls.crt
  - HEIMDALL_SERVER_CONTROL_TLS_KEY_PATH=/etc/heimdall/certs/tls.key
  name: heimdall-control-plane-config
images:
- name: heimdall-control-plane
  newName: ghcr.io/rafaeljc/heimdall/control-plane
  newTag: sha-eb83b55
