apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- hpa.yaml
- external-secret.yaml
- service-public.yaml

patches:
- path: deployment-patch.yaml

# Kustomize automatically hashes this ConfigMap. Modifying any value will trigger a seamless rolling update of the pods.
      # Enforce TLS on the gRPC Data Plane
configMapGenerator:
- literals:
  - HEIMDALL_APP_ENV=production
  - HEIMDALL_APP_LOG_LEVEL=info
  - HEIMDALL_APP_LOG_FORMAT=json
  - HEIMDALL_REDIS_TLS_ENABLED=true
  - HEIMDALL_SERVER_DATA_TLS_ENABLED=true
  - HEIMDALL_SERVER_DATA_TLS_CERT_PATH=/etc/heimdall/certs/tls.crt
  - HEIMDALL_SERVER_DATA_TLS_KEY_PATH=/etc/heimdall/certs/tls.key
  name: heimdall-data-plane-config
images:
- name: heimdall-data-plane
  newName: ghcr.io/rafaeljc/heimdall/data-plane
  newTag: sha-eb83b55
